# You can configure this file to customize your site
globals:
    # Definition of global variable
    title : Site Title
    description : Site Description
    url : Site Url
    logo : /content/images/logo.jpg
blocks:
    # All blocks to compile
    post:
        source  : /posts/
        target  : /posts/
    category:
        source  :
            default : Default
        template  : categories.twig
        target    : categories.html
    tag:
        template  : tags.twig
        target    : tags.html
    archive:
        template  : archives.twig
        target    : archives.html
    index:
        template  : index.twig
        target    : index.html
        limit     : 10
    about:
        template  : about.twig
        target    : about.html
feeds:
    # Definition of feeds gererating
    source  : post
    recent  : 20
    target  : feeds.xml
    author  : Logecho
build:
    # The commands running after compile
    - cp -f @THEME/crisp.css @TARGET/crisp.css
    - cp -f @THEME/prism.css @TARGET/prism.css
    - cp -f @THEME/typo.css @TARGET/typo.css
    - cp -f @THEME/base.js @TARGET/base.js
    - cp -f @THEME/prism.js @TARGET/prism.js
    - cp -f @THEME/jquery.scrollUp.js @TARGET/jquery.scrollUp.js
    - cp -rf @THEME/../content/* @TARGET/content
sync:
    # The commands running with sync operation
