# You can configure this file to customize your site
globals:
    # Definition of global variable
    title : Site Title
    description : Site Description
    url : Site Url
    logo : /content/images/logo.jpg
blocks:
    # All blocks to compile
    post:
        source  : /posts/
        target  : /posts/
    category:
        source  :
            default : Default
        template  : archives.twig
        target    : archives.html
    tag:
        template  : archives.twig
        target    : archives.html
    archive:
        template  : archives.twig
        target    : archives.html
    index:
        template  : index.twig
        target    : index.html
        limit     : 10
feeds:
    # Definition of feeds gererating
    source  : post
    recent  : 20
    target  : feeds.xml
    author  : Logecho
build:
    # The commands running after compile
    - cp -f @THEME/crisp.css @TARGET/crisp.css
    - cp -f @THEME/base.js @TARGET/base.js
    - cp -rf @THEME/../content/* @TARGET/content
sync:
    # The commands running with sync operation
